### ISSUE TITLE
More descriptive start method name

### ISSUE THREAD

**Issue by weshenderson** [Factual/braze-factual-engine-ios#2]
Just looking over the basic API, I found "startIntegration" to be not very informative (i.e., what does the "integration" do?)
https://github.com/Factual/braze-factual-engine-ios/blob/bb24ffb8e8dceaf4cba035cd480d2b16994d9e8a/library/BrazeEngine/BrazeEngine.h#L44

In the Segment integration, we had "trackUserJourney" `[AnalyticsEngineUtil trackUserJourneyWithEngine:engine forAnalytics:[SEGAnalytics sharedAnalytics]];`. A descriptive name like this would be helpful to clarify what the method does. How about something like "trackUserJourneyAndCircumstancesWithEngine:" or "trackEventsWithEngine:"?

**Comment by zevada** [comment]
05a43cda2fe0d8e58a9c8a6408990e549c7b3734
